name: gestureface
description: Système d'authentification biométrique double facteur simultané (visage + geste main) avec protection des données, panic mode et camouflage.
publish_to: 'none'
version: 3.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & State
  rxdart: ^0.28.0
  provider: ^6.1.2
  crypto: ^3.0.3

  # Camera & Vision
  camera: ^0.10.5+9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fake_gallery/
